//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song_Category
    {
        public long Song_ID { get; set; }
        public long Category_ID { get; set; }
        public string Detail { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Song Song { get; set; }
    }
}
